// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package inno_agent

import (
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/xh-polaris/inno_agent/biz/api/model/basicuser"
	"github.com/xh-polaris/inno_agent/biz/api/model/system"
)

type SystemService interface {
	system.SystemService
}

type SystemServiceClient struct {
	*system.SystemServiceClient
}

func NewSystemServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *SystemServiceClient {
	return &SystemServiceClient{
		SystemServiceClient: system.NewSystemServiceClientFactory(t, f),
	}
}

func NewSystemServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *SystemServiceClient {
	return &SystemServiceClient{
		SystemServiceClient: system.NewSystemServiceClientProtocol(t, iprot, oprot),
	}
}

func NewSystemServiceClient(c thrift.TClient) *SystemServiceClient {
	return &SystemServiceClient{
		SystemServiceClient: system.NewSystemServiceClient(c),
	}
}

type UserService interface {
	basicuser.UserService
}

type UserServiceClient struct {
	*basicuser.UserServiceClient
}

func NewUserServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: basicuser.NewUserServiceClientFactory(t, f),
	}
}

func NewUserServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: basicuser.NewUserServiceClientProtocol(t, iprot, oprot),
	}
}

func NewUserServiceClient(c thrift.TClient) *UserServiceClient {
	return &UserServiceClient{
		UserServiceClient: basicuser.NewUserServiceClient(c),
	}
}

type SystemServiceProcessor struct {
	*system.SystemServiceProcessor
}

func NewSystemServiceProcessor(handler SystemService) *SystemServiceProcessor {
	self := &SystemServiceProcessor{system.NewSystemServiceProcessor(handler)}
	return self
}

type UserServiceProcessor struct {
	*basicuser.UserServiceProcessor
}

func NewUserServiceProcessor(handler UserService) *UserServiceProcessor {
	self := &UserServiceProcessor{basicuser.NewUserServiceProcessor(handler)}
	return self
}
